"""initial schema

Revision ID: 45059cb11e48
Revises: 
Create Date: 2026-05-05 21:51:58.867453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '45059cb11e48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.Enum('WORDPRESS', 'CUSTOM', name='sitemode', native_enum=False, length=16), server_default='wordpress', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_slug'), 'sites', ['slug'], unique=True)
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('task_type', sa.Enum('CREATE_PAGE', 'UPDATE_PAGE', 'ROLLBACK_PAGE', 'BULK_SEMANTICS', name='jobtasktype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', 'MANUAL_REVIEW', name='jobrunstatus', native_enum=False, length=32), server_default='pending', nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=True),
    sa.Column('page_ids', sa.JSON(), nullable=True),
    sa.Column('iteration_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('turgenev_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('tech_log', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_celery_task_id'), 'job_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_job_runs_site_id'), 'job_runs', ['site_id'], unique=False)
    op.create_index('ix_job_runs_site_idempotency', 'job_runs', ['site_id', 'idempotency_key'], unique=False)
    op.create_index(op.f('ix_job_runs_status'), 'job_runs', ['status'], unique=False)
    op.create_index(op.f('ix_job_runs_task_type'), 'job_runs', ['task_type'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'PUBLISHED', 'MANUAL_REVIEW', 'FAILED', name='pagestatus', native_enum=False, length=32), server_default='draft', nullable=False),
    sa.Column('page_type', sa.String(length=64), nullable=True),
    sa.Column('keyword_raw', sa.Text(), nullable=True),
    sa.Column('keyword_hash', sa.String(length=64), nullable=True),
    sa.Column('wp_post_id', sa.BigInteger(), nullable=True),
    sa.Column('seo_overrides', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'keyword_hash', name='uq_pages_site_keyword_hash'),
    sa.UniqueConstraint('site_id', 'slug', name='uq_pages_site_slug')
    )
    op.create_index(op.f('ix_pages_page_type'), 'pages', ['page_type'], unique=False)
    op.create_index(op.f('ix_pages_site_id'), 'pages', ['site_id'], unique=False)
    op.create_index(op.f('ix_pages_status'), 'pages', ['status'], unique=False)
    op.create_index(op.f('ix_pages_wp_post_id'), 'pages', ['wp_post_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_page_id'), 'media', ['page_id'], unique=False)
    op.create_index(op.f('ix_media_site_id'), 'media', ['site_id'], unique=False)
    op.create_table('page_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_revisions_page_id'), 'page_revisions', ['page_id'], unique=False)
    op.create_table('processed_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('keyword_hash', sa.String(length=64), nullable=False),
    sa.Column('keyword_normalized', sa.Text(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('job_run_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'keyword_hash', name='uq_processed_site_kw_hash')
    )
    op.create_index(op.f('ix_processed_keywords_keyword_hash'), 'processed_keywords', ['keyword_hash'], unique=False)
    op.create_index(op.f('ix_processed_keywords_site_id'), 'processed_keywords', ['site_id'], unique=False)
    op.create_table('manual_review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('job_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='manualreviewstatus', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('last_turgenev_score', sa.Float(), nullable=True),
    sa.Column('turgenev_remarks', sa.JSON(), nullable=True),
    sa.Column('last_revision_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_revision_id'], ['page_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_review_queue_job_run_id'), 'manual_review_queue', ['job_run_id'], unique=False)
    op.create_index(op.f('ix_manual_review_queue_page_id'), 'manual_review_queue', ['page_id'], unique=False)
    op.create_index(op.f('ix_manual_review_queue_site_id'), 'manual_review_queue', ['site_id'], unique=False)
    op.create_index(op.f('ix_manual_review_queue_status'), 'manual_review_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_review_queue_status'), table_name='manual_review_queue')
    op.drop_index(op.f('ix_manual_review_queue_site_id'), table_name='manual_review_queue')
    op.drop_index(op.f('ix_manual_review_queue_page_id'), table_name='manual_review_queue')
    op.drop_index(op.f('ix_manual_review_queue_job_run_id'), table_name='manual_review_queue')
    op.drop_table('manual_review_queue')
    op.drop_index(op.f('ix_processed_keywords_site_id'), table_name='processed_keywords')
    op.drop_index(op.f('ix_processed_keywords_keyword_hash'), table_name='processed_keywords')
    op.drop_table('processed_keywords')
    op.drop_index(op.f('ix_page_revisions_page_id'), table_name='page_revisions')
    op.drop_table('page_revisions')
    op.drop_index(op.f('ix_media_site_id'), table_name='media')
    op.drop_index(op.f('ix_media_page_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_pages_wp_post_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_status'), table_name='pages')
    op.drop_index(op.f('ix_pages_site_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_page_type'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_job_runs_task_type'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_status'), table_name='job_runs')
    op.drop_index('ix_job_runs_site_idempotency', table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_site_id'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_celery_task_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_sites_slug'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
